services:
  regex-forge:
    build:
      context: https://github.com/Fuzarth/regex-forge.git
    image: regex-forge:latest
    container_name: regex_forge
    ports:
      - "8109:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
